<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VesselSeeder extends Seeder
{
    public function run(): void
    {
        $vessels = [
            ['vessel_id' => 'MHI', 'vessel_name' => 'MANALAGI HITA'],
            ['vessel_id' => 'MSM', 'vessel_name' => 'MANALAGI SAMBA'],
            ['vessel_id' => 'MPR', 'vessel_name' => 'MANALAGI PRITA'],
            ['vessel_id' => 'MEN', 'vessel_name' => 'MANALAGI ENZI'],
            ['vessel_id' => 'MTI', 'vessel_name' => 'MANALAGI TISYA'],
            ['vessel_id' => 'MAR', 'vessel_name' => 'MANALAGI TARA'],
            ['vessel_id' => 'MVI', 'vessel_name' => 'MANALAGI VIRA'],
            ['vessel_id' => 'MDA', 'vessel_name' => 'MANALAGI DASA'],
            ['vessel_id' => 'MWA', 'vessel_name' => 'MANALAGI WANDA'],
            ['vessel_id' => 'MYA', 'vessel_name' => 'MANALAGI YASA'],
            ['vessel_id' => 'MAA', 'vessel_name' => 'MANALAGI ASTA'],
            ['vessel_id' => 'MIA', 'vessel_name' => 'MANALAGI ASTI'],
            ['vessel_id' => 'XSA', 'vessel_name' => 'XYS SATU'],
            ['vessel_id' => 'HSJ', 'vessel_name' => 'HIJAU SEJUK'],
            ['vessel_id' => 'ODI', 'vessel_name' => 'ORIENTAL DIAMOND'],
            ['vessel_id' => 'OJA', 'vessel_name' => 'ORIENTAL JADE'],
            ['vessel_id' => 'ORU', 'vessel_name' => 'ORIENTAL RUBY'],
            ['vessel_id' => 'OSA', 'vessel_name' => 'ORIENTAL SAMUDERA'],
            ['vessel_id' => 'VEI', 'vessel_name' => 'VERIZON'],
            ['vessel_id' => 'HAN', 'vessel_name' => 'SPIL HANA'],
            ['vessel_id' => 'HAP', 'vessel_name' => 'SPIL HAPSRI'],
            ['vessel_id' => 'HAS', 'vessel_name' => 'SPIL HASYA'],
            ['vessel_id' => 'HAY', 'vessel_name' => 'SPIL HAYU'],
            ['vessel_id' => 'HJE', 'vessel_name' => 'HIJAU JELITA'],
            ['vessel_id' => 'PSM', 'vessel_name' => 'PEKAN SAMPIT'],
            ['vessel_id' => 'AKA', 'vessel_name' => 'AKASHIA'],
            ['vessel_id' => 'DER', 'vessel_name' => 'DERAJAT'],
            ['vessel_id' => 'FOR', 'vessel_name' => 'FORTUNE'],
            ['vessel_id' => 'KAA', 'vessel_name' => 'KAPPA'],
            ['vessel_id' => 'MAG', 'vessel_name' => 'MAGELLAN'],
            ['vessel_id' => 'RAT', 'vessel_name' => 'SPIL RATNA'],
            ['vessel_id' => 'RUM', 'vessel_name' => 'SPIL RUMI'],
            ['vessel_id' => 'HSA', 'vessel_name' => 'HIJAU SAMUDRA'],
            ['vessel_id' => 'MBU', 'vessel_name' => 'MINAS BARU'],
            ['vessel_id' => 'OGO', 'vessel_name' => 'ORIENTAL GOLD'],
            ['vessel_id' => 'SBR', 'vessel_name' => 'SELILI BARU'],
            ['vessel_id' => 'TIT', 'vessel_name' => 'TITANIUM'],
            ['vessel_id' => 'VER', 'vessel_name' => 'VERTIKAL'],
            ['vessel_id' => 'APE', 'vessel_name' => 'ARMADA PERMATA'],
            ['vessel_id' => 'LUZ', 'vessel_name' => 'LUZON'],
            ['vessel_id' => 'OGA', 'vessel_name' => 'ORIENTAL GALAXY'],
            ['vessel_id' => 'PBE', 'vessel_name' => 'PEKAN BERAU'],
            ['vessel_id' => 'PBI', 'vessel_name' => 'PEKAN BINTANG'],
            ['vessel_id' => 'PFA', 'vessel_name' => 'PEKAN FAJAR'],
            ['vessel_id' => 'PRI', 'vessel_name' => 'PEKAN RIAU'],
            ['vessel_id' => 'ASG', 'vessel_name' => 'ARMADA SEGARA'],
            ['vessel_id' => 'ASN', 'vessel_name' => 'ARMADA SENADA'],
            ['vessel_id' => 'ASR', 'vessel_name' => 'ARMADA SERASI'],
            ['vessel_id' => 'MAN', 'vessel_name' => 'MULI ANIM'],
            ['vessel_id' => 'OEM', 'vessel_name' => 'ORIENTAL EMERALD'],
            ['vessel_id' => 'OSI', 'vessel_name' => 'ORIENTAL SILVER'],
            ['vessel_id' => 'BAU', 'vessel_name' => 'BALI AYU'],
            ['vessel_id' => 'BGI', 'vessel_name' => 'BALI GIANYAR'],
            ['vessel_id' => 'BKU', 'vessel_name' => 'BALI KUTA'],
            ['vessel_id' => 'BSA', 'vessel_name' => 'BALI SANUR'],
            ['vessel_id' => 'PAH', 'vessel_name' => 'PAHALA'],
            ['vessel_id' => 'PST', 'vessel_name' => 'PRATIWI SATU'],
            ['vessel_id' => 'KLE', 'vessel_name' => 'KALIMANTAN ECO'],
            ['vessel_id' => 'SLA', 'vessel_name' => 'SULAWESI ECO'],
            ['vessel_id' => 'RAH', 'vessel_name' => 'SPIL RAHAYU'],
            ['vessel_id' => 'RET', 'vessel_name' => 'SPIL RETNO'],
            ['vessel_id' => 'REN', 'vessel_name' => 'SPIL RENATA'],
            ['vessel_id' => 'OPA', 'vessel_name' => 'ORIENTAL PACIFIC'],
            ['vessel_id' => 'PRA', 'vessel_name' => 'PRATIWI RATA'],
            ['vessel_id' => 'PNN', 'vessel_name' => 'PULAU NUNUKAN'],
            ['vessel_id' => 'THT', 'vessel_name' => 'THETA'],
            ['vessel_id' => 'PGL', 'vessel_name' => 'PGL 01'],
            ['vessel_id' => 'ALP', 'vessel_name' => 'TB ALPHA SATU'],
            ['vessel_id' => 'GST', 'vessel_name' => 'TB GAMMA SATU'],
            ['vessel_id' => 'TOY', 'vessel_name' => 'TB TOYO'],
            ['vessel_id' => 'ALA', 'vessel_name' => 'BC ANGSA LAUT'],
            ['vessel_id' => 'BAA', 'vessel_name' => 'BC BELAWAN RAYA'],
            ['vessel_id' => 'BAY', 'vessel_name' => 'BC BAYA'],
            ['vessel_id' => 'BRA', 'vessel_name' => 'BC BALIKPAPAN RAYA'],
            ['vessel_id' => 'BRY', 'vessel_name' => 'BC BANJARMASIN RAYA'],
            ['vessel_id' => 'EPS', 'vessel_name' => 'BC EPSILON'],
            ['vessel_id' => 'GLA', 'vessel_name' => 'BC GAJAH LAUT'],
            ['vessel_id' => 'GMA', 'vessel_name' => 'BC GAJAH MADA'],
            ['vessel_id' => 'GSA', 'vessel_name' => 'TB GAJAH SATU'],
            ['vessel_id' => 'KIN', 'vessel_name' => 'BC KAIMANA INDAH'],
            ['vessel_id' => 'M05', 'vessel_name' => 'BC MURO 5'],
            ['vessel_id' => 'M03', 'vessel_name' => 'TB MURO 3'],
            ['vessel_id' => 'SBA', 'vessel_name' => 'BC SHORYU BARU'],
            ['vessel_id' => 'YYU', 'vessel_name' => 'TB YITNA YUWANA'],
            ['vessel_id' => 'SRA', 'vessel_name' => 'BC SAMARINDA RAYA'],
            ['vessel_id' => 'SRY', 'vessel_name' => 'BC SURABAYA RAYA'],
            ['vessel_id' => 'TEN', 'vessel_name' => 'BC TENYO'],
            ['vessel_id' => 'YBA', 'vessel_name' => 'TB YUSHIN BARU'],
            ['vessel_id' => 'TRA', 'vessel_name' => 'BC TARAKAN RAYA'],
            ['vessel_id' => 'ZET', 'vessel_name' => 'TK ZETA'],
            ['vessel_id' => 'MRA', 'vessel_name' => 'TB MANGGA RAYA'],
            ['vessel_id' => 'BET', 'vessel_name' => 'TK BETA'],
            ['vessel_id' => 'DDU', 'vessel_name' => 'TK DELTA DUA'],
            ['vessel_id' => 'SIG', 'vessel_name' => 'MT SIGMA'],
            ['vessel_id' => 'HSG', 'vessel_name' => 'HIJAU SEGAR'],
            ['vessel_id' => 'PHK', 'vessel_name' => 'PULAU HOKI'],
            ['vessel_id' => 'PLA', 'vessel_name' => 'PULAU LAYANG'],
            ['vessel_id' => 'PWE', 'vessel_name' => 'PULAU WETAR'],
            ['vessel_id' => 'TBE', 'vessel_name' => 'TELUK BERAU'],
            ['vessel_id' => 'TBI', 'vessel_name' => 'TELUK BINTUNI'],
            ['vessel_id' => 'TFL', 'vessel_name' => 'TELUK FLAMINGGO'],
        ];

        DB::table('vessels')->insert($vessels);
    }
}