<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VesselMainPowerSeeder extends Seeder
{
    public function run(): void
    {
        // satuan vc_main_power: kW
        $data = [
            ['vessel_id' => 'MHI', 'vc_main_power' => '7908'],
            ['vessel_id' => 'MSM', 'vc_main_power' => '7800'],
            ['vessel_id' => 'MPR', 'vc_main_power' => '8550'],
            ['vessel_id' => 'MEN', 'vc_main_power' => '8702'],
            ['vessel_id' => 'MTI', 'vc_main_power' => '8171'],
            ['vessel_id' => 'MAR', 'vc_main_power' => '9480'],
            ['vessel_id' => 'MVI', 'vc_main_power' => '9480'],
            ['vessel_id' => 'MDA', 'vc_main_power' => '16680'],
            ['vessel_id' => 'MWA', 'vc_main_power' => '9480'],
            ['vessel_id' => 'MYA', 'vc_main_power' => '7756'],
            ['vessel_id' => 'MAA', 'vc_main_power' => null],
            ['vessel_id' => 'MIA', 'vc_main_power' => null],
            ['vessel_id' => 'XSA', 'vc_main_power' => '9480'],
            ['vessel_id' => 'HSJ', 'vc_main_power' => '7274'],
            ['vessel_id' => 'ODI', 'vc_main_power' => null],
            ['vessel_id' => 'OJA', 'vc_main_power' => '10139'],
            ['vessel_id' => 'ORU', 'vc_main_power' => '10139'],
            ['vessel_id' => 'OSA', 'vc_main_power' => '2940'],
            ['vessel_id' => 'VEI', 'vc_main_power' => null],
            ['vessel_id' => 'HAN', 'vc_main_power' => '2529'],
            ['vessel_id' => 'HAP', 'vc_main_power' => '2529'],
            ['vessel_id' => 'HAS', 'vc_main_power' => '2975'],
            ['vessel_id' => 'HAY', 'vc_main_power' => '2975'],
            ['vessel_id' => 'HJE', 'vc_main_power' => '7982'],
            ['vessel_id' => 'PSM', 'vc_main_power' => '1814'],
            ['vessel_id' => 'AKA', 'vc_main_power' => '1765'],
            ['vessel_id' => 'DER', 'vc_main_power' => '1765'],
            ['vessel_id' => 'FOR', 'vc_main_power' => '1765'],
            ['vessel_id' => 'KAA', 'vc_main_power' => '1765'],
            ['vessel_id' => 'MAG', 'vc_main_power' => '1765'],
            ['vessel_id' => 'RAT', 'vc_main_power' => '2575'],
            ['vessel_id' => 'RUM', 'vc_main_power' => '2575'],
            ['vessel_id' => 'HSA', 'vc_main_power' => '11050'],
            ['vessel_id' => 'MBU', 'vc_main_power' => '2574'],
            ['vessel_id' => 'OGO', 'vc_main_power' => null],
            ['vessel_id' => 'SBR', 'vc_main_power' => '2574'],
            ['vessel_id' => 'TIT', 'vc_main_power' => '2574'],
            ['vessel_id' => 'VER', 'vc_main_power' => '2574'],
            ['vessel_id' => 'APE', 'vc_main_power' => '5992'],
            ['vessel_id' => 'LUZ', 'vc_main_power' => '11071'],
            ['vessel_id' => 'OGA', 'vc_main_power' => '11680'],
            ['vessel_id' => 'PBE', 'vc_main_power' => '895'],
            ['vessel_id' => 'PBI', 'vc_main_power' => '1765'],
            ['vessel_id' => 'PFA', 'vc_main_power' => '1618'],
            ['vessel_id' => 'PRI', 'vc_main_power' => '1618'],
            ['vessel_id' => 'ASG', 'vc_main_power' => '6037'],
            ['vessel_id' => 'ASN', 'vc_main_power' => '6037'],
            ['vessel_id' => 'ASR', 'vc_main_power' => '4502'],
            ['vessel_id' => 'MAN', 'vc_main_power' => '1498'],
            ['vessel_id' => 'OEM', 'vc_main_power' => '9761'],
            ['vessel_id' => 'OSI', 'vc_main_power' => '9761'],
            ['vessel_id' => 'BAU', 'vc_main_power' => '1765'],
            ['vessel_id' => 'BGI', 'vc_main_power' => '1765'],
            ['vessel_id' => 'BKU', 'vc_main_power' => '1765'],
            ['vessel_id' => 'BSA', 'vc_main_power' => '1765'],
            ['vessel_id' => 'PAH', 'vc_main_power' => '1765'],
            ['vessel_id' => 'PST', 'vc_main_power' => '2000'],
            ['vessel_id' => 'KLE', 'vc_main_power' => '4119'],
            ['vessel_id' => 'SLA', 'vc_main_power' => null],
            ['vessel_id' => 'RAH', 'vc_main_power' => null],
            ['vessel_id' => 'RET', 'vc_main_power' => '2206'],
            ['vessel_id' => 'REN', 'vc_main_power' => '2206'],
            ['vessel_id' => 'OPA', 'vc_main_power' => '2940'],
            ['vessel_id' => 'PRA', 'vc_main_power' => '1471'],
            ['vessel_id' => 'PNN', 'vc_main_power' => '3356'],
            ['vessel_id' => 'THT', 'vc_main_power' => '596'],
            ['vessel_id' => 'PGL', 'vc_main_power' => '3824'],
            ['vessel_id' => 'ALP', 'vc_main_power' => '544'],
            ['vessel_id' => 'GST', 'vc_main_power' => '818'],
            ['vessel_id' => 'TOY', 'vc_main_power' => '2160'],
            ['vessel_id' => 'ALA', 'vc_main_power' => '441'],
            ['vessel_id' => 'BAA', 'vc_main_power' => '956'],
            ['vessel_id' => 'BAY', 'vc_main_power' => '302'],
            ['vessel_id' => 'BRA', 'vc_main_power' => '552'],
            ['vessel_id' => 'BRY', 'vc_main_power' => '441'],
            ['vessel_id' => 'EPS', 'vc_main_power' => '441'],
            ['vessel_id' => 'GLA', 'vc_main_power' => '515'],
            ['vessel_id' => 'GMA', 'vc_main_power' => null],
            ['vessel_id' => 'GSA', 'vc_main_power' => null],
            ['vessel_id' => 'KIN', 'vc_main_power' => '883'],
            ['vessel_id' => 'M05', 'vc_main_power' => null],
            ['vessel_id' => 'M03', 'vc_main_power' => '405'],
            ['vessel_id' => 'SBA', 'vc_main_power' => null],
            ['vessel_id' => 'YYU', 'vc_main_power' => '485'],
            ['vessel_id' => 'SRA', 'vc_main_power' => '736'],
            ['vessel_id' => 'SRY', 'vc_main_power' => '324'],
            ['vessel_id' => 'TEN', 'vc_main_power' => '300'],
            ['vessel_id' => 'YBA', 'vc_main_power' => '353'],
            ['vessel_id' => 'TRA', 'vc_main_power' => '257'],
            ['vessel_id' => 'ZET', 'vc_main_power' => null],
            ['vessel_id' => 'MRA', 'vc_main_power' => '759'],
            ['vessel_id' => 'BET', 'vc_main_power' => null],
            ['vessel_id' => 'DDU', 'vc_main_power' => null],
            ['vessel_id' => 'SIG', 'vc_main_power' => '1118'],
            ['vessel_id' => 'HSG', 'vc_main_power' => '7497'],
            ['vessel_id' => 'PHK', 'vc_main_power' => '2059'],
            ['vessel_id' => 'PLA', 'vc_main_power' => '2800'],
            ['vessel_id' => 'PWE', 'vc_main_power' => '2059'],
            ['vessel_id' => 'TBE', 'vc_main_power' => '2060'],
            ['vessel_id' => 'TBI', 'vc_main_power' => '2060'],
            ['vessel_id' => 'TFL', 'vc_main_power' => '2060'],
        ];

        foreach ($data as $item) {
            DB::table('vessels')->where('vessel_id', $item['vessel_id'])->update(['vc_main_power' => $item['vc_main_power']]);
        }
    }
}
